### ISSUE TITLE
Problem compiling in Arduino IDE

### ISSUE THREAD

**Issue by delinend** [liebman/ESPNTPServer#2]
Hi liebman.

I'm trying to compile you ESPNTPServer via Arduino IDE 1.8.1 (have maked an empty ESPNTPServer.ino file)
But I'm stranding on this error, in the ESPNTPServer.cpp:

sketch\ESPNTPServer.cpp: In function 'void logTimeFirst(DLogBuffer&, DLogLevel)':

ESPNTPServer.cpp:49: error: aggregate 'timeval tv' has incomplete type and cannot be defined

     struct timeval tv;

                    ^

sketch\ESPNTPServer.cpp: In function 'void loop()':

ESPNTPServer.cpp:262: error: aggregate 'timeval tv' has incomplete type and cannot be defined

     struct timeval tv;

                    ^

exit status 1
aggregate 'timeval tv' has incomplete type and cannot be defined

Best regards

**Comment by delinend** [comment]
Solved the problem, by upgrading the ESP8266 Board from 2.3.0 to 2.4.1 in Arduino IDE

**Comment by liebman** [comment]
Actually - this project is set up as a "sketch book"  - At some point I should update the README to describe how to set that up.  This way I can manage the exact version of the core and various libraries, they are all included as git submodules..

**Comment by delinend** [comment]
Thanks for reply and great work, liebman. The ESPNTPServer project, works great on my ESP-07 module and a NEO-7M GPS with PPS output :-)

**Comment by d0ugak** [comment]
I had trouble compiling this under the latest 1.8.8 Arduino IDE even after downgrading the board library version. Since the 1st post mentioned IDE 1.8.1 I downgraded to that and it compiled with no issues.

I now have this running on a Wemos D1 mini clone, One of these BLOX 6M OpenSmart GPS receivers I had laying around https://www.dx.com/p/open-smart-serial-gps-module-for-arduino-apm2-5-flight-control-2080189 and the recommended OLED display. 

Since the pin labels on a Wemos D1 mini don't translate to the actual GPIO# of the ESP8266 The following are the pins you would attach to if you build with this platform.

SCL = D1
SDA = D2
PPS = D6
TXD = D7
CFG = D5

I was curious if this would have better jitter and offset reporting from ntpq -p since it uses the PPS pin, but does not seem to resolve that much better than another ESP/GPS/NTP project I originally tried from http://absolutelyautomation.com/articles/2016/09/15/esp8266-based-wireless-ntp-server-no-internet-connection-needed I guess the issues with jitter and offset are inherent in using the ESP8226 platform and wifi possibly?
